# Generated by Django 3.2.11 on 2022-02-07 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
