# Generated by Django 3.2.11 on 2022-02-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_background_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='mobile',
            new_name='dist',
        ),
    ]
